# ========================================================
# SkyPOS Profile: DEV (Local Development)
# ========================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Flyway can be enabled on-demand in dev
spring.flyway.enabled=false

# Verbose debug logging for local developers
logging.level.root=INFO
logging.level.com.bluesky.pos_system=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG

# Actuator full details
management.endpoint.health.show-details=always
